Repository imdrasil/jennifer.cr, pull requests merged in 2018-10, with the labels that each got.

#172 Refactor query object
  docs/model_mapping.md
  docs/query_dsl.md
  docs/validation.md
  spec/model/base_spec.cr
  spec/models.cr
  src/jennifer/adapter.cr
  src/jennifer/config.cr
  src/jennifer/macros.cr
  src/jennifer/migration/base.cr
  src/jennifer/migration/runner.cr
  src/jennifer/migration/version.cr
  src/jennifer/model/base.cr
  src/jennifer/model/scoping.cr
  src/jennifer/model/translation.cr
  src/jennifer/query_builder/aggregations.cr
  src/jennifer/query_builder/criteria.cr
  src/jennifer/query_builder/query.cr
  src/jennifer/query_builder/query_object.cr
  src/jennifer/view/base.cr
  src/jennifer/view/materialized.cr
Labels: enhancement

#177 Remove Model::Base.build_params
  docs/model_mapping.md
  spec/model/base_spec.cr
  spec/model/mapping_spec.cr
  spec/model/parameter_converter_spec.cr
  spec/model/sti_mapping_spec.cr
  spec/query_builder/model_query_spec.cr
  src/jennifer/model/base.cr
  src/jennifer/model/mapping.cr
  src/jennifer/model/parameter_converter.cr
  src/jennifer/model/sti_mapping.cr
Labels: enhancement

#170 Feature/validation macros enhancements
  .github/pull_request_template.md
  docs/validation.md
  spec/model/validation_spec.cr
  spec/models.cr
  spec/support/matchers.cr
  spec/validations/inclusion_spec.cr
  src/jennifer.cr
  src/jennifer/model/errors.cr
  src/jennifer/model/validation.cr
  src/jennifer/validations/absence.cr
  src/jennifer/validations/acceptance.cr
  src/jennifer/validations/confirmation.cr
  src/jennifer/validations/exclusion.cr
  src/jennifer/validations/format.cr
  src/jennifer/validations/inclusion.cr
  src/jennifer/validations/length.cr
  src/jennifer/validations/macros.cr
  src/jennifer/validations/numericality.cr
  src/jennifer/validations/presence.cr
  src/jennifer/validations/uniqueness.cr
  src/jennifer/validations/validator.cr
  src/jennifer/validator.cr
Labels: enhancement, next minor release

#178 Fix links to similar shards
  README.md
Labels: bug
