Repository imdrasil/jennifer.cr, pull requests merged in 2018-09, with the labels that each got.

#158 Populate native exception from the driver during quering
  .travis.spec.sh
  docs/configuration.md
  shard.yml
  spec/adapter/base_spec.cr
  spec/integration/concurrency_test.cr
  spec/model/base_spec.cr
  spec/spec_helper.cr
  src/jennifer/adapter/base.cr
  src/jennifer/adapter/base_sql_generator.cr
  src/jennifer/adapter/transactions.cr
  src/jennifer/config.cr
  src/jennifer/model/converters.cr
Labels: bug, enhancement

#161 Fix custom port not used in postgres adapter
  src/jennifer/adapter/postgres/command_interface.cr
Labels: enhancement

#164 Return true when save persisted unchanged model
  spec/model/base_spec.cr
  src/jennifer/model/base.cr
Labels: bug

#165 Adjust documentation generating
  spec/model/base_spec.cr
  spec/model/mapping_spec.cr
  spec/model/sti_mapping_spec.cr
  spec/view/base_spec.cr
  spec/view/experimental_mapping_spec.cr
  src/jennifer.cr
  src/jennifer/adapter.cr
  src/jennifer/adapter/postgres/migration/table_builder/change_enum.cr
  src/jennifer/adapter/shared/types.cr
  src/jennifer/migration/base.cr
  src/jennifer/migration/table_builder/base.cr
  src/jennifer/migration/table_builder/change_table.cr
  src/jennifer/migration/table_builder/create_table.cr
  src/jennifer/model/base.cr
  src/jennifer/model/callback.cr
  src/jennifer/model/mapping.cr
  src/jennifer/model/relation_definition.cr
  src/jennifer/model/resource.cr
  src/jennifer/model/scoping.cr
  src/jennifer/model/sti_mapping.cr
  src/jennifer/model/translation.cr
  src/jennifer/model/validation.cr
  src/jennifer/query_builder/aggregations.cr
  src/jennifer/query_builder/query.cr
  src/jennifer/relation/base.cr
  src/jennifer/relation/belongs_to.cr
  src/jennifer/relation/relation_stub.cr
  src/jennifer/view/base.cr
  src/jennifer/view/experimental_mapping.cr
Labels: bug

#168 Create and change table method enhancements
  .travis.spec.sh
  Makefile
  README.md
  examples/migrations/20170119011451314_create_contacts.cr
  examples/migrations/20170119011507724_create_address.cr
  spec/adapter/base_spec.cr
  spec/migration/table_builder.cr
  spec/migration/table_builder/change_table_spec.cr
  spec/migration/table_builder/create_foreign_key_spec.cr
  spec/migration/table_builder/create_table_spec.cr
  spec/migration/table_builder/create_view_spec.cr
  spec/migration/table_builder/drop_table_spec.cr
  spec/migration/table_builder/drop_view_spec.cr
  spec/migration/table_builder/spec_helper.cr
  spec/model/base_spec.cr
  spec/models.cr
  src/jennifer/migration/table_builder/base.cr
  src/jennifer/migration/table_builder/change_table.cr
  src/jennifer/migration/table_builder/create_table.cr
Labels: bug

#169 Allow order definition by Criteria
  README.md
  docs/pagination_and_ordering.md
  spec/adapter/mysql/.keep
  spec/adapter/mysql/sql_generator_spec.cr
  spec/adapter/postgres/sql_generator_spec.cr
  spec/adapter/sql_generator_spec.cr
  spec/query_builder/criteria_container_spec.cr
  spec/query_builder/order_item_spec.cr
  spec/query_builder/ordering_spec.cr
  spec/support/matchers.cr
  src/jennifer/adapter/base.cr
  src/jennifer/adapter/base_sql_generator.cr
  src/jennifer/adapter/mysql/sql_generator.cr
  src/jennifer/adapter/postgres/sql_generator.cr
  src/jennifer/query_builder/condition.cr
  src/jennifer/query_builder/criteria.cr
  src/jennifer/query_builder/criteria_container.cr
  src/jennifer/query_builder/executables.cr
  src/jennifer/query_builder/grouping.cr
  src/jennifer/query_builder/logic_operator.cr
  src/jennifer/query_builder/order_item.cr
  src/jennifer/query_builder/ordering.cr
  src/jennifer/query_builder/query.cr
  src/jennifer/query_builder/sql_node.cr
Labels: enhancement

#171 Fix typos in Readme
  README.md
Labels: bug
