Repository imdrasil/jennifer.cr, pull requests merged in 2019-03, with the labels that each got.

#223 Add query upsert command
  .travis.yml
  spec/query_builder/executables_spec.cr
  src/jennifer/adapter/base.cr
  src/jennifer/adapter/base_sql_generator.cr
  src/jennifer/adapter/mysql/sql_generator.cr
  src/jennifer/adapter/postgres/criteria.cr
  src/jennifer/adapter/postgres/sql_generator.cr
  src/jennifer/model/base.cr
  src/jennifer/query_builder/aggregations.cr
  src/jennifer/query_builder/executables.cr
  src/jennifer/query_builder/expression_builder.cr
  src/jennifer/query_builder/values.cr
Labels: enhancement

#221 Refactor resource mapping
  examples/migrations/20170407022844409_create_profile.cr
  spec/model/mapping_spec.cr
  spec/model/sti_mapping_spec.cr
  spec/model/validation_spec.cr
  spec/view/base_spec.cr
  spec/view/mapping_spec.cr
  spec/views.cr
  src/jennifer/model/base.cr
  src/jennifer/model/mapping.cr
  src/jennifer/model/relation_definition.cr
  src/jennifer/model/resource.cr
  src/jennifer/model/sti_mapping.cr
  src/jennifer/query_builder/model_query.cr
  src/jennifer/relation/polymorphc_belongs_to.cr
  src/jennifer/view/base.cr
  src/jennifer/view/experimental_mapping.cr
  src/jennifer/view/mapping.cr
  src/jennifer/view/materialized.cr
Labels: chore

#222 Add common table expression
  .ci/database.yml
  .ci/setup.sh
  .ci/test.sh
  .travis.setup.sh
  .travis.yml
  README.md
  docs/eager_loading.md
  docs/query_dsl.md
  examples/setup.sh
  spec/adapter/base_sql_generator_spec.cr
  spec/query_builder/common_table_expression_spec.cr
  spec/query_builder/eager_loading_spec.cr
  spec/query_builder/executables_spec.cr
  spec/query_builder/model_query_spec.cr
  spec/query_builder/multi_query_relation_tree_spec.cr
  spec/query_builder/ordering_spec.cr
  spec/query_builder/query_spec.cr
  src/jennifer/adapter/base_sql_generator.cr
  src/jennifer/adapter/mysql/sql_generator.cr
  src/jennifer/adapter/postgres/sql_generator.cr
  src/jennifer/query_builder/aggregations.cr
  src/jennifer/query_builder/common_table_expression.cr
  src/jennifer/query_builder/eager_loading.cr
  src/jennifer/query_builder/executables.cr
  src/jennifer/query_builder/i_model_query.cr
  src/jennifer/query_builder/joining.cr
  src/jennifer/query_builder/model_query.cr
  src/jennifer/query_builder/ordering.cr
  src/jennifer/query_builder/query.cr
  src/jennifer/relation/polymorphic_belongs_to.cr
Labels: enhancement

#219 Allow custom field names for mapped columns
  examples/migrations/20181017202211501_create_column_alias_models.cr
  spec/factories.cr
  spec/model/base_spec.cr
  spec/model/mapping_spec.cr
  spec/model/sti_mapping_spec.cr
  spec/models.cr
  spec/view/mapping_spec.cr
  spec/views.cr
  src/jennifer/model/mapping.cr
  src/jennifer/model/sti_mapping.cr
  src/jennifer/validations/macros.cr
  src/jennifer/view/mapping.cr
Labels: enhancement

#225 Fix odd and even options of numericality validator
  spec/spec_helper.cr
  spec/support/matchers.cr
  spec/validations/absence_spec.cr
  spec/validations/acceptance_spec.cr
  spec/validations/confirmation_spec.cr
  spec/validations/exclusion_spec.cr
  spec/validations/format_spec.cr
  spec/validations/inclusion_spec.cr
  spec/validations/length_spec.cr
  spec/validations/numericality_spec.cr
  spec/validations/presence_spec.cr
  spec/validations/uniqueness_spec.cr
  src/jennifer/validations/numericality.cr
Labels: bug

#227 Add #merge query method
  spec/query_builder/query_spec.cr
  src/jennifer/query_builder/query.cr
Labels: enhancement

#226 #join enhancements
  spec/adapter/base_sql_generator_spec.cr
  spec/model/mapping_spec.cr
  spec/query_builder/executables_spec.cr
  spec/query_builder/function_spec.cr
  spec/query_builder/joining_spec.cr
  spec/spec_helper.cr
  src/jennifer/model/base.cr
  src/jennifer/model/mapping.cr
  src/jennifer/model/resource.cr
  src/jennifer/query_builder/aggregations.cr
  src/jennifer/query_builder/all.cr
  src/jennifer/query_builder/any.cr
  src/jennifer/query_builder/condition.cr
  src/jennifer/query_builder/eager_loading.cr
  src/jennifer/query_builder/executables.cr
  src/jennifer/query_builder/expression_builder.cr
  src/jennifer/query_builder/function.cr
  src/jennifer/query_builder/i_model_query.cr
  src/jennifer/query_builder/join.cr
  src/jennifer/query_builder/joining.cr
  src/jennifer/query_builder/query.cr
  src/jennifer/view/base.cr
Labels: enhancement

#228 Add `CAST` sql method
  spec/adapter/base_sql_generator_spec.cr
  spec/query_builder/cast_spec.cr
  src/jennifer/adapter/base_sql_generator.cr
  src/jennifer/query_builder/cast.cr
  src/jennifer/query_builder/expression_builder.cr
Labels: enhancement
